image_width: 640
image_height: 480
camera_name: front_left
camera_matrix:
  rows: 3
  cols: 3
  data: [394.55729,   0.     , 322.60748,
           0.     , 394.85789, 245.61055,
           0.     ,   0.     ,   1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.315894, 0.080007, 0.000770, -0.000247, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [289.77194,   0.     , 323.28098,   0.     ,
           0.     , 339.87186, 247.79107,   0.     ,
           0.     ,   0.     ,   1.     ,   0.     ]
