image_width: 640
image_height: 480
camera_name: side_left
camera_matrix:
  rows: 3
  cols: 3
  data: [397.24043,   0.     , 326.09324,
           0.     , 397.62324, 234.89465,
           0.     ,   0.     ,   1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.326283, 0.088544, 0.000802, -0.000720, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [292.82126,   0.     , 327.6512 ,   0.     ,
           0.     , 341.64725, 233.14537,   0.     ,
           0.     ,   0.     ,   1.     ,   0.     ]
