image_width: 640
image_height: 480
camera_name: side_right
camera_matrix:
  rows: 3
  cols: 3
  data: [401.16257,   0.     , 319.78601,
           0.     , 401.55694, 245.99952,
           0.     ,   0.     ,   1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.313691, 0.075854, -0.000211, -0.001038, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [296.09561,   0.     , 316.71862,   0.     ,
           0.     , 347.90652, 247.45619,   0.     ,
           0.     ,   0.     ,   1.     ,   0.     ]
