procs:
    s_graphs:
        shell: 'bash -c "source /workspace/install/setup.bash && ros2 launch lidar_situational_graphs s_graphs_launch.py lidar_topic:=/cloud/undistorted base_frame:=base_link compute_odom:=false"'
        autostart: true
    fast_lio:
        shell: 'bash -c "source /workspace/install/setup.bash && ros2 launch fast_lio mapping.launch.py config_file:=ouster64.yaml rviz:=false"'
        autostart: true
    rviz:
        shell: 'bash -c "source /workspace/install/setup.bash && rviz2 -d /workspace/src/s_graphs/lidar_situational_graphs/rviz/s_graphs_ros2.rviz"'
        autostart: true
