ouster/os_driver:
    ros__parameters:
        sensor_hostname: "os-122436001165.local"
        # mtp_main[optional]: if true, then configure and reinit the sensor,
        # otherwise start client with active configuration of sensor
        mtp_main: true
        # lidar_mode[optional]: resolution and rate; possible values: { 512x10,
        # 512x20, 1024x10, 1024x20, 2048x10, 4096x5 }. Leave empty to remain on
        # current the lidar mode.
        lidar_mode: "1024x10"
        # timestamp_mode[optional]: method used to timestamp measurements; possible
        # values:
        # - TIME_FROM_INTERNAL_OSC
        # - TIME_FROM_SYNC_PULSE_IN
        # - TIME_FROM_PTP_1588
        # - TIME_FROM_ROS_TIME: This option uses the time of reception of first
        #                       packet of a LidarScan as the timestamp of the IMU,
        #                       PointCloud2 and LaserScan messages.
        timestamp_mode: "TIME_FROM_ROS_TIME"
        # ptp_utc_tai_offset[optional]: UTC/TAI offset in seconds to apply when
        # TIME_FROM_PTP_1588 timestamp mode is used.
        ptp_utc_tai_offset: -37.0
        udp_profile_lidar: "RNG19_RFL8_SIG16_NIR16"
        metadata: "/home/smapper/smapper/config/os-122436001165-metadata.json"
        lidar_port: 46750
        imu_port: 37267
        sensor_frame: os_sensor
        lidar_frame: os_lidar
        imu_frame: os_imu
        point_cloud_frame: os_lidar
        pub_static_tf: false
        # proc_mask[optional]: use any combination of the 6 flags IMG, PCL, IMU, SCAN
        # RAW and TLM to enable or disable their respective messages.
        # proc_mask: IMU|PCL|SCAN|IMG|RAW|TLM
        proc_mask: IMU|PCL
        # use_system_default_qos[optional]: if false, data are published with sensor
        # data QoS. This is preferrable for production but default QoS is needed for
        # rosbag. See: https://github.com/ros2/rosbag2/issues/125
        use_system_default_qos: true
        point_type: original
        persist_config: false
        attempt_reconnect: true
        max_failed_reconnect_attempts: 20
        min_range: 0.0
        max_range: 1000.0
