image_width: 640
image_height: 480
camera_name: front_left
camera_matrix:
  rows: 3
  cols: 3
  data: [394.95415,   0.     , 322.97698,
           0.     , 395.72233, 244.27315,
           0.     ,   0.     ,   1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.318874, 0.083961, 0.001218, -0.000634, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [291.51575,   0.     , 322.90865,   0.     ,
           0.     , 340.66119, 246.30165,   0.     ,
           0.     ,   0.     ,   1.     ,   0.     ]
