image_width: 640
image_height: 480
camera_name: side_left
camera_matrix:
  rows: 3
  cols: 3
  data: [395.39655,   0.     , 311.04736,
           0.     , 395.45385, 245.96602,
           0.     ,   0.     ,   1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.327656, 0.089694, 0.000190, 0.000875, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [290.72742,   0.     , 307.30475,   0.     ,
           0.     , 338.69516, 247.87073,   0.     ,
           0.     ,   0.     ,   1.     ,   0.     ]
