enable_color: true
rgb_camera:
    color_profile: 640x480x30

enable_depth: true
depth_module:
    depth_profile: 640x480x30
    infra_profile: 640x480x30

align_depth.enable: true

enable_sync: true

enable_gyro: true
enable_accel: true
unite_imu_method: 2 # 0-None, 1-copy, 2-linear_interpolation
gyro_fps: 400
accel_fps: 200

pointcloud.enable: true
# colorizer.enable: true

publish_tf: true
# tf_publish_rate: 1.0
